---
<font color='Blue' size="4">
F37.204 컴퓨팅 핵심: 컴퓨터로 생각하기(Core Computing: Thinking with Computers)</font>

---


# Chapter 2. 복합자료형과 제어문


:::{admonition} 학습목표와 기대효과
:class: info  
- 학습목표
  - 리스트, 딕셔너리, 튜플, 집합, 배열 등의 복합자료형을 빠르게 훑어본다.
  - 조건문과 반복문도 빠르게 훑어본다.
  - **코드 축약법에 대해 익혀보자.**
  - **복합자료형의 특성을 파악하고 가변 자료형과 불변 자료형의 개념을 이해하자.**
  - **얕은 복사와 깊은 복사에 대해서 알아보자.**

- 기대효과
  - 다수의 데이터를 저장하기 위해 적절한 자료형을 선택할 수 있고 다룰 수 있다.
:::

## 리스트


리스트 생성
- 리스트는 숫자, 문자, 리스트, 딕셔너리 등 어떠한 데이터 타입이든 다 담을 수 있는 만물박스이다.
- 형식은 다음과 같다.


```
[아이템1, 아이템2, 아이템3, ..., 아이템n]
```



- 리스트는 대괄호 안에 아이템을 콤마로 나열하여 생성할 수 있다.
- 아이템없이 대괄호만 있으면 비어있는 리스트를 생성한다.

In [ ]:
a = [1, 2, 3, 4, 5]
b = [3, 8, 1, 3, 2]
c = [1, 'apple', ['banana',1, 2], 'coconut']
d = ['apple', 'banana', 'coconut', 'durian']
e = [ ]

- list() 함수로 생성
  - list() 함수는 빈 리스트, 숫자리스트, 문자열을 낱개문자로 분리하여 리스트로 만드는 함수이다.
  - range()함수와 같이 사용하면 수열로 이루어진 리스트를 생성한다.
  - list() 괄호안에 문자열을 넣어주면 각 문자로 분리하여 리스트를 생성한다.

In [ ]:
item = list()
a=list(range(1,10))
print(a)
a=list('hello')
print(a)

- .split() 메서드로 생성
  - split() 함수는 문자열을 특정 기준에 따라 분리하여 리스트로 만드는 함수이다.

```
'문자열'.split(공백 또는 지정한 문자열)
```

In [ ]:
item = '바나나, 딸기, 복숭아'
fruit = item.split(', ')
print(fruit)

리스트 주요 메서드

|사용 방법|의미|예시(a=['a','b','c']일 때)|
|:----------:|:----------|:----------|
|`list.append(item)`|list의 마지막에 item을 추가| a.append('d') ➡ ['a','b','c','d'] |
|`list.extend(list2)`|list의 마지막에 list2의 아이템을 추가하여 확장| a.extend(['d','e']) ➡ ['a','b','c','d','e']|
|`list.insert(index, item)`|list의 index 위치에 item을 삽입| a.insert(1,'d') ➡ ['a','d','c','d']|
|`list.remove(item)`|list에서 첫 번째로 나오는 item을 삭제|a.remove('c') ➡ ['a','b']|
|`list.index(item)`|list에서 item의 index를 반환|a.index('c') ➡ 2|
|`list.count(item)`|list에서 item의 개수를 반환|a.count('c') ➡ 1|
|`list.clear()`|list의 모든 item의 제거한다.|a.clear() ➡ []|
|`list.pop(index)`|list에서 인덱스의 아이템을 제거하고 반환.<br> 인덱스를 지정하지 않으면 마지막 아이템을 제거하고 반환|a.pop(1) ➡ ['a','c']|
|`list.reverse()`|list에서 아이템의 순서를 뒤집는다.|a.reverse() ➡ ['c','b','a']|
|`list.copy()`|list를 shallow copy한다.|b=a.copy() ➡ b= ['a','b','c']|
|`list.sort()`|list 내 item를 오름차순으로 정렬| a = ['c','a','b']일 때, a.sort() ➡ ['a', 'b', 'c']|
|`list2 = sorted(list)`|list를 오름차순으로 정렬하여 반환|b = sorted(a) ➡  b = ['a', 'b', 'c']|

리스트 연산자

|연산 기호|의미|예시|실행 결과|
|:----------:|:----------:|:----------:|:--------:|
|`+`|아이템합치기|`[1,2,3]+['a','b']`|`[1,2,3,'a','b']`|
|`*`|아이템을 횟수만큼 합치기|`[1,2,3]*2`|`[1,2,3,1,2,3]`|

In [ ]:
a = [1,2,3]
b = [5,6,7]
print(a+b)

In [ ]:
a=[1,2,3]
print(a*3)

## 딕셔너리


인덱스는 항상 정수로만 해야 할까?라는 생각을 한 번 쯤은 해본 적이 있을지도 모른다. 딕셔너리는 이러한 생각을 깨고 key를 인덱스로 사용한다.

딕셔너리의 형식은 다음과 같다.

```
{Key1:Value1, Key2:Value2, Key3:Value3, ...}
```
- 딕셔너리는 key와 value가 쌍(pair)으로 이루어진 자료구조이며, 중괄호 { }로 묶는다.
- 딕셔너리의 key로는 숫자, 문자열, 튜플(숫자,문자열,튜플만 원소로 갖고 있는) 등 불변(immutable) 데이터타입만 사용할 수 있다.
- 딕셔너리의 value에는 숫자, 문자열, 리스트, 튜플, 집합, 딕셔너리까지 다양한 자료형이 들어갈 수 있다.

딕셔너리 생성
- 중괄호 { }안에 key:value 쌍을 콤마로 나열하여 직접 생성할 수 있다.
- 또한 dict() 함수안에 (key, value) 쌍을 순서적으로 넣어 생성할 수 있다.
- `변수명 = dict()`나 `변수명 = {}`와 같이 쓰면 비어있는 딕셔너리를 생성한다.


In [ ]:
dict1 = {'name':'Byun', 'phone':'010-111-2222', 'birth': '09/08', 'data':[1, 2, 3]}
dict2 = dict([('L0444.000400', '컴퓨팅기초' ), ('L0444.000500', '컴퓨팅핵심'), ('L0444.000600', '컴퓨팅응용')])
dict3 = dict()
dict4 = {}

print(dict1)
print(dict2)
print(dict3)
print(dict4)

딕셔너리 주요 메서드

|사용 방법|의미|예시 sports = { '걷기' : 4, '조깅': 7, '수영': 9}|
|:----------:|:----------|:----------|
|`dict.get(key)`|딕셔너리에 key가 있으면 그 key와 매핑하는 value을 반환하고<br> key가 없으면 반환없음| sports.get('걷기') ➡ 4 |
|`dict.items()`|딕셔너리의 아이템들을 리스트 형태로 반환 | sports.items() ➡ dict_items([('걷기', 4), ('조깅', 7), ('수영', 9)])|
|`dict.keys()`|딕셔너리의 모든 key를 리스트 형태로 반환 | sports.keys() ➡ dict_keys(['걷기', '조깅', '수영'])|
|`dict.values()`|딕셔너리의 모든 value을 리스트 형태로 반환 | sports.values() ➡ dict_values([4, 7, 9]))|
|`dict.pop(key)`|딕셔너리의 key를 찾아 제거하고 value를 반환 | sports.pop('조깅') ➡ 7|
|`dict.update(dict2)`|다른 딕셔너리와 합함, 반환은 없음| sports.update({'피겨':10, '축구': 10, '야구': 9}) ➡ sports = {'걷기' : 4, '조깅': 7, '수영': 9, '피겨': 10, '축구': 10, '야구': 9}|
|`dict.clear()`|딕셔너리의 모든 아이템을 삭제| sports.clear() ➡ { }|

## 튜플


튜플 생성
- 리스트와 마찬가지로 숫자, 문자, 리스트, 딕셔너리 등 어떠한 데이터 타입이든 다 담을 수 있는 만물박스이다.
- 괄호( )안에 아이템을 콤마로 나열하여 직접 생성할 수 있다.
- tuple() 함수의 괄호안에 아이템들을 순서적으로 넣어 생성할 수 있다.
- `변수명 = tuple()`나 `변수명 = ()`와 같이 쓰면 비어있는 튜플을 생성한다.
- 아이템을 하나만 가진 튜플을 생성할 때에는 `변수명 = (1,)`와 같이 콤마 하나를 넣어줘야 한다. 이는 숫자 (1)로 인식하는 것을 피하기 위해서이다.

In [ ]:
t1 = ()
t2 = (1,)
t3 = (1, 2, 3)
t4 = 1, 2, 3
t5 = ( 'a', 'b', ('ab', 'cd') )
a = {'name':'Byun', 'phone':'010-111-2222', 'birth': '09/08', 'data':[1, 2, 3]}
t6 = tuple(a.keys())
t7 = tuple()
print( t1, t2, t3, t4, t5, t6, t7, sep='\n' )

튜플 주요 메서드

- 리스트에서와는 달리 아이템의 수정, 삭제, 추가, 삽입은 불가능하다.
- 따라서 append(), insert(), remove(), clear(), pop(), reverse(), sort(), copy() 등의 메서드는 지원하지 않는다.


|사용 방법|의미|예시<br> std_ID = ('23345', '23346', '23346', '23347')|
|:----------:|:----------|:----------|
|tuple.index(item)|tuple에서 item의 index를 반환| std_ID.index('23347') ➡ 3 |
|tuple.count(item)|tuple에서 item의 개수를 반환 | std_ID.count('23346') ➡ 2|


## 집합


리스트에서는 index를, 딕셔너리에서는 key를 사용하여 value에 접근할 수 있었다. 그렇다면 index나 key는 반드시 필요할까?

집합(set)은 index나 key가 없다. 그렇기 때문에 순서가 없으며, 값이 중복되지 않는 특징을 가진 자료구조이다. 수학의 집합과 개념적으로 아주 비슷하다.

집합 생성
- 중괄호 { }안에 아이템을 콤마로 나열하여 직접 생성할 수 있다.
- 또한 `변수명 = set()`와 같이 쓰면 비어있는 set을 생성할 수 있다.
- set은 아이템의 중복을 수용하지 않기 때문에 중복을 제거할 필요가 있는 데이터라면 set으로 만들면 된다.

In [ ]:
s1 = {'foo', 'bar', 'baz', 'foo', 'qux'}
s2 = set()
s3 = set([1,1,4,2,2,6,6,6,6,7,8,10,4,2,8,6,3])
print(s1, s2, s3, sep='\n')

집합 주요 메서드

|사용 방법|의미|예시<br> a={1,4,7} b={1,3,6,8,10}|
|:----------:|:----------|:----------|
|a.add(element) |추가 | a.add(5) ➡ {1,4,5,7}|
|a.union(b) or <br> a\|b |합집합 | a\|b ➡ {1, 3, 4, 6, 7, 8, 10}|
|a.difference(b) or <br> a-b|차집합 | a-b ➡ {4, 7}|
|a.intersection(b) or <br> a&b|교집합 | a&b ➡ {1}|
|a.symmetric_difference(b) or <br> a^b|대칭차집합 | a^b ➡ {3, 4, 6, 7, 8, 10}|

이외에도 몇 가지 메서드가 있으니 살펴보기 바란다.

## 배열



배열(Array) 생성
- numpy는 Number와 python의 합성어이다.
- 행렬이나 대규모 다차원 배열을 쉽고 빠르게 처리할 수 있도록 하는 파이썬 라이브러리이며, 간단한 기능부터 계산과학 분야의 복잡한 연산을 지원하기 위한 기능들까지 포함되어 있다.
- numpy의 배열에는 모두 동일한 자료형만 저장이 가능하다.

In [ ]:
import numpy as np

- 1차원 배열부터 만들어보자.
- numpy모듈에서는 배열을 생성하는 다양한 방법을 지원한다.
  - numpy 모듈의 `array()`를 통해 배열을 만들 수 있다.
  - numpy 모듈의 `arange()`를 통해 배열을 만들 수 있다.


```
np.array(리스트 or range())
np.arange(start, end, step)
```



In [ ]:
ar1 = np.array([1,2,3,4,5])
ar11 = np.array(range(10))
ar111= np.arange(1,6)
print(ar1)
print(ar11)
print(ar111)

- 2차원 배열은 행(Row)과 열(Column)로 구성되어 있다.
<div align="center"><img src="https://haesunbyun.github.io/Core-Computing/_images/ch11/array.png" style="width:400px;"></div>

- 행은 가로 방향으로 줄을 세운 것이며, 열은 세로 방향으로 줄을 세운 것이다.
- 2차원 배열은 array()에 중첩 리스트를 넣어주거나, 배열모양을 바꿔주는 reshape()을 통해서 생성할 수 있다.

```
np.array([리스트 of 리스트])
np.arange(start,end,step).reshape(row, column)
```
- 여기서 row는 행의 개수, column은 열의 개수이다. column을 -1로 써주면 각 행에 들어갈 데이터의 개수를 동일하게 적용해준다.

- 이때 배열 원소의 개수와 row*column의 개수가 같아야 한다.



In [ ]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
ar22 = np.arange(1,13).reshape(4,3)
ar222 = ar2.reshape(3,-1)
print(ar2)
print('========')
print(ar22)
print('========')
print(ar222)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- 3차원 배열은 면(page), 행, 열을 가진다.
- 생성하는 방법은 2차원 배열과 유사하지만 리스트가 3번 중첩된다.

```
np.array([리스트 of 리스트 of 리스트])
np.arange(start,end,step).reshape(page, row, column)
```

In [ ]:
ar3 = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])
ar33 = np.arange(1,13).reshape(2,2,3)
print(ar3)
print('========')
print(ar33)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- 배열의 구성, 차수 등의 정보를 확인하기 위해서는 다음과 같은 변수를 쓸 수 있다.

```
배열명.ndim
배열명.shape
배열명.size
```
  - ndim: 배열의 축 또는 차원의 개수
  - shape: 배열의 모양이며, (m,n)형식으로 나타난다.
  - size: 배열 원소의 개수. shape내의 원소의 크기의 곱과 같다. 즉 shape의 m*n은 size와 같다.

In [ ]:
print(ar3.ndim)
print(ar3.shape)
print(ar3.size)

배열 연산
- numpy에서는 동일 인덱스끼리의 연산을 지원한다.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

- 배열 x를 활용하여 배열 y를 구해보자.

> $y=2x^2-3x+1$


In [ ]:
x = np.arange(0, 5, 0.1)
y = 2*(x**2)-3*x+1
print(x)
print(y)

- numpy는 행렬끼리 연산할때 크기가 다른 경우 이를 자동으로 확대해 주는 브로드캐스팅을 지원한다.

<div align="center"><img src="https://haesunbyun.github.io/common/images/broadcasting.png" style="width:400px;"></div>



In [ ]:
ar0 = np.arange(12).reshape(4, 3)
ar1 = np.arange(3)

print(ar0)
print('========')
print(ar1)

In [ ]:
ar0 + ar1

- 논리연산의 경우 아래의 기호뿐만 아니라 논리적인 연산을 할 수 있는 함수(logical_and(), logical_or(),logical_not()..)도 존재한다.
  - and는 `&`,
  - or는 `|`,
  - not은 `~`로 쓴다.

In [ ]:
a = np.array([160,175,157])
c = np.array(['여','여','남'])
print((a>162) | ~(c=='여'))

배열의 응용
- 데이터 분석 예: 날씨 데이터를 분석. 특정 기간 동안의 온도 데이터를 분석해 평균, 최대, 최소 값을 계산

In [ ]:
import numpy as np

# 예제: 일주일간의 온도 데이터 (섭씨)
temperatures = np.array([22.1, 23.4, 21.8, 22.9, 23.0, 24.2, 23.5])

# 평균 온도
mean_temp = np.mean(temperatures)

# 최대 온도
max_temp = np.max(temperatures)

# 최소 온도
min_temp = np.min(temperatures)

print(f"평균 온도: {mean_temp:.2f}°C")
print(f"최대 온도: {max_temp:.2f}°C")
print(f"최소 온도: {min_temp:.2f}°C")


- 이미지 처리의 예: 이미지를 흑백으로 변환하거나 필터를 적용할 때 NumPy를 사용할 수 있다.


In [ ]:
import numpy as np
from PIL import Image

# 이미지 로드

image = Image.open('example.jpg')
image_np = np.array(image)
print(image_np)

# 회색조 변환
gray_image_np = np.mean(image_np, axis=2).astype(np.uint8)

# 변환된 이미지 저장
gray_image = Image.fromarray(gray_image_np)
gray_image.save('example_gray.jpg')


### 배열과 리스트의 비교
- 얼핏 비슷해 보이지만 완전히 기능이 다른
파이썬의 리스트(list)와 numpy의 배열(array)의 차이를 간단히 비교해보자.

- 리스트와 배열의 생성에서,
  - 리스트는 정수, 실수, 문자열, 리스트 등 다양한 자료형을 하나의 리스트에 담을 수 있다.
  - 배열은 동일한 자료형만 하나의 배열에 담을 수 있다.
  - 배열은 numpy.ndarray 타입이다.


In [ ]:
its_list = ['바나나', '딸기', 100, 5.5,['BTS', '블랙핑크']]
its_array = np.array([1, 2, 3.0])
its_array1 = np.array([1, 2, '3.0'])
its_array2 = np.array([1, 2, None])
print(its_list)
print(its_array)
print(its_array1)
print(its_array2)

- 리스트와 배열에 곱셈연산을 해보았을 때,
  - 리스트에서 곱셈은 리스트를 이어 붙이는 concatenate이다. 즉, 각 원소에 곱셈을 하지 않는다.
  - 배열은 각 원소에 벡터연산을 한다.


In [ ]:
print(its_list*2)
print('========')
print(its_array*2)

- 리스트와 배열의 연산속도
  - 리스트와 배열의 연산속도를 확인해보자.
  - 억개의 숫자에 대해서 2를 곱했다.
  - 결과를 보면 배열(array)가 10배 이상 빠르다.
  - 배열은 동일한 자료형만 저장하므로 데이터 저장에 필요한 저장공간이 일정하며 연속적이다. 따라서 메모리 주소 측면에서 인덱스를 통해 빠르게 데이터에 접근할 수 있다.
  - 반면, 리스트는 다양한 자료형을 저장할 수 있어서 필요한 저장공간이 일정하지 않으며, 메모리 활동공간도 연속적이지 않다. 인덱스를 갖지만 이는 몇 번째 데이터인가 정도를 의미한다.

```python
import time
a = list(range(10 ** 8))

start = time.time()
[i *2 for i in a]
end = time.time()
print(f'리스트 실행시간: {end - start}')

a = np.array(range(10 ** 8))
start = time.time()
a * 2
end = time.time()
print(f'배열 실행시간: {end - start}')
```



## 인덱싱(Indexing)과 슬라이싱

- **인덱스**는 데이터의 순서를 나타내는 주소이다. 즉, 아이템에 접근하기 위해 인덱스를 사용한다.
- 문자열, 리스트, 튜플, 배열 등은 정수인덱스가 사용되므로 잘 익혀두기 바란다.

- 숫자 인덱스의 경우, 양의 인덱스(positive index)와 음의 인덱스(negative index)가 있다.
- 양의 인덱스는 가장 왼쪽 문자에서 0부터 시작하여 오른쪽으로 증가한다.
- 음의 인덱스는 가장 오른쪽 끝 아이템에서 -1부터 시작하여 왼쪽으로 감소한다.

In [ ]:
#문자열
a = "Life is too short, You need Python"
print( a[0], a[1], a[2], a[3] )

#리스트
shape= ['turtle', 'arrow', ['banana',1, 2], 'square']
print(shape[0], shape[1], shape[2][0] )

# 튜플
t5 = ( 'a', 'b', ('ab', 'cd') )
print(t5[0])

# 배열
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
ar2[1][1]

#딕셔너리
sports = { '걷기' : 4, '조깅': 7, '수영': 9}
print(sports['걷기'])

# 집합
s1 = {'foo', 'bar', 'baz', 'foo', 'qux'}
# set은 순서가 없어서 인덱싱할 수가 없다.


In [ ]:
print( a[-1], a[-2], a[-3], a[-4] ) #문자열
print(shape[-1], shape[-2]) #리스트
print(t5[-1]) #튜플
ar2[-1][-2] #배열

슬라이싱(Slicing)이란 데이터의 부분을 취하는 것이다. 형식은 다음과 같다.

```
변수[start:end:step]
```
- 여기서 변수는 리스트, 문자열, 튜플 등의 다수 데이터를 저장하고 인덱스로 접근 할 수 있는 자료형 변수를 의미한다.
- start: 시작 인덱스. 디폴트는 step이 양수이면 시작 인덱스는 0, step이 음수이면 시작 인덱스는 -1이다.
- end: 끝 인덱스. 끝 인덱스 -1까지 슬라이싱 된다.
- step: 이동간격. 양수이면 오른쪽으로 step만큼 이동한다. 음수이면 왼쪽으로 step만큼 이동한다.

- start, end, step 모두 생략 가능하다.

- 아래의 코드를 통해 실습해보자.
- 시작 인덱스의 생략으로 처음부터 인덱스 3 이전까지 오른쪽으로 이동하여 슬라이싱한다.

In [ ]:
a = "Life is too short, You need Python"
print(a[ :3])

shape= ['turtle', 'arrow', ['banana',1, 2], 'square']
print(shape[ : 2])

t5 = ( 'a', 'b', ('ab', 'cd') )
print(t5[-3: -1])

# 배열
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
ar2[1: , 1:]

## 프로그래밍 제어구조


:::{admonition} 프로그래밍 제어구조
:class: info  

프로그래밍의 제어구조로는 코드의 순서대로 실행하는 순차구조, 조건에 따라 실행을 분기하는 조건(선택)구조, 일정 부분을 반복하여 실행하는 반복구조가 있다.

프로그램의 흐름(flow)를 파악하기 위해 차례대로 보기 쉽게 그린 그림을 플로우차트라고 한다.
:::

<div align="center"><img src="https://haesunbyun.github.io/Basic-Computing/_images/ch03/flow.png" style="width:600px;"></div>

앞서 우리는 프로그램의 코드를 순서대로 실행시키는 순차구조에 대해서 익혀왔다. 이번에는 특정 조건에 따라 실행을 분기시키는 조건구조에 대해서 알아보자.

## 연산자


### 비교연산자

비교연산자는 정수, 문자열, 변수 등의 값을 비교할 때 사용한다. <font color='red'> 비교연산자의 결과는 bool 타입인 True 또는 False로 나온다. </font>

비교연산자의 종류는 다음과 같다.

|연산 기호|의미|예시|실행 결과|
|:----------:|:----------:|:----------:|:--------:|
|`>`|크다|`2 > 1`|`True`|
|`<`|작다|`2 < 1`|`False`|
|`>=`|크거나 같다|`2 >= 1`|`True`|
|`<=`|작거나 같다|`2 <= 1`|`False`|
|`==`|같다|`1 == '1'`|`False`|
|`!=`|같지 않다|`1 != '1'`|`True`|

### 멤버연산자

멤버연산자는 어떤 값이 포함되어 있는지 아닌지를 검사하는 연산자이다. 멤버연산자의 결과는 항상 True 또는 False로 나온다.

|연산 기호|의미|예시|실행 결과|
|:----------:|:----------:|:----------:|:--------:|
|`in`|포함되어 있다|`'p' in 'python'`|`True`|
|`not in`|포함되어 있지 않다|`'p' not in 'python'`|`False`|

### 논리 연산자
한개 또는 두개 이상의 조건을 비교하여 논리적인 결과를 얻고자 할때 사용한다. 논리연산자의 결과는 항상 True 또는 False로 나온다.  
- 논리연산자는 not > and > or로 우선순위를 가진다. 우선순위가 동일한 경우에는 왼쪽에서 오른쪽 순서로 실행한다.

|연산 기호|의미|예시|실행 결과|
|:----------:|:----------:|:----------:|:--------:|
|`and`|논리곱(그리고)|`True and False`|`False`|
|`or`|논리합(또는)|`True or False`|`True`|
|`not`|논리부정(아니다)|`not False`|`True`|

## 조건문

if문은 조건에 따라 실행을 분기시키는 문으로 if문, if ~ else문, if ~ elif ~ else문이 있다.
- 조건식의 끝에는 반드시 콜론(:)을 붙여야 한다.
- 조건식에 변수가 들어간다면 반드시 미리 정의되어 있어야 한다.
- 조건에 의해서 실행되는 문장들은 반드시 들여쓰기(Indentation)을 해야 한다.

### if 문
- 비교해야 할 조건식이 하나라면 if문으로 충분하다.

In [ ]:
score = 75
if score >= 75:
  print("success!")

### if ~ else 문
- 비교해야 할 조건식이 True일때와 False일때를 분기하여 실행해야 한다면 if ~ else문이 적합하다.
- 아래 코드에서 print('Happy')는 조건에 의해 실행되는 문장이 아니다. 따라서 들여쓰기가 되어 있지 않다.

In [ ]:
score = 75
if score >= 75:
  print("success!")
else:
  print("Fail")

### if ~ elif ~ else 문(다중 if문)
- 중첩 if ~ else문 대신에 다중 if문(if ~ elif ~ elif ~ else)으로 코드를 간결화 할 수 있다.
- 다중 if문은 조건식이 True인 조건을 만날 때 까지 비교하면서 내려온다.
- 조건식이 True인 조건을 만나면 그 조건에 해당하는 실행문장을 실행한 후, 다음 elif문의 조건을 비교하지 않고 다중 if문 전체를 벗어난다.

In [ ]:
a=10
b=7
c=3
query=5
if query>a:
  print("가장 큰 수 이다.")
elif query>b:  # query<a and query>b
  print("두 번째로 큰 수 이다.")
elif query>c:
  print("세 번째로 큰 수 이다.")
else: #없을수도 있음
  print("가장 작은 수 이다.")


## 반복문: while
반복(iteration)문은 동일한 문장을 반복해서 실행하는 구조이다.
반복문 while과 for에 대해서 알아본다.


### while statement
while문의 형식은 다음과 같다. 조건 뒤에는 반드시 콜론(:)이 있어야 하며, 조건이 True인 동안 while문 안에 있는 실행 문장을 실행한다. 이때 실행 문장은 반드시 들여쓰기가 되어 있어야 한다.

```
while 조건:
    실행 문장1
    실행 문장2
    ...
```

In [ ]:
count = 1
while count <= 5:
    print(f'재미있는 파이썬:{count}')
    count=count+1

print(f'count={count}')

### break

- while문의 조건 부분에 조건식이 아닌 True 또는 1 등을 넣어줄 수도 있다.
- 이 경우에는 `while True:` 또는 `while 1:` 이므로 조건이 항상 True가 되어 무한 반복하게 된다.
- 따라서 무한반복문의 경우 반드시 반복문을 탈출하는 break를 반복문 안 어딘가에 있어야 한다.




In [ ]:
count = 0
while True :
    print(f'무야호~:{count}')
    count = count + 1
    if count == 5:
       break
print(f'count={count}')

### while ~ else
- while문에도 else가 있다.
- while문의 else 파트는 while문이 정상적으로 모든 반복을 다 한 경우에만 실행한다.
- 즉, while문의 조건식이 False가 되서 빠져나오는 경우에만 실행하며, break를 통해서 while문을 빠져나온 경우에는 else문이 실행되지 않는다.



```python
count = 0
while count < 5 :
    pw=input('Password: ')
    if pw=='pythonisfun':
       print('로그인 되었습니다.')
       break
    count = count + 1    
else:
    print ('로그인에 실패했습니다.')
```



## 반복문: for

while문이 주어진 조건에 대해 반복하는 것이였다면 for문은 주어진 범위에 대해 순회한다.


### for statements

```
for 변수 in 범위(반복가능한 것들):
    statements
next_statements
```
- while문에서는 조건에 사용될 변수를 while문 전에 미리 정의해야 했다. 그러나 for문에서는 for 다음에 바로 정의하면 된다.
- 범위에는 range, 문자열, 리스트, 튜플, 딕셔너리 등  반복가능한 데이터 타입(iterable data type)들이 올 수 있다.


In [ ]:
for count  in range(1, 11):
    print(f'🌳를 {count}그루 심었습니다. {"🌳"*count}')
print('아~ 공기좋다~~~')

In [ ]:
for count  in range(1, 11, 2):
    print(f'🌳를 {count}그루 심었습니다. {"🌳"*count}')
print('아~ 공기좋다~~~')

- `범위에 문자열`을 넣을 수 있다. 문자열의 경우 변수 i가 한 글자씩 순회한다.

In [ ]:
for i in 'Hello World':
    if i == 'o':
      print('wow')

- 반복문 범위에 `리스트`를 넣을 수 있다. 리스트의 경우 변수 i가 리스트내 아이템(원소, 요소, 엘리먼트)를 하나씩 순회한다.


In [ ]:
for i in ['programming', 'pasta', 'spam', 'play park']:
  if i[0] =='p':
    print (i)

- 반복문 범위에 `딕셔너리`를 넣을 수 있다. 딕셔너리의 경우 변수 i가 딕셔너리의 key를 하나씩 순회한다.


In [ ]:
for i in {'2323-12345':'가영', '2323-12346':'나영'}:
    print (i)

- 반복문의 범위에 `집합`을 넣을 수 있다. 변수 i가 집합의 원소를 하나씩 순회한다. 그러나 집합은 순서가 없기 때문에 출력하는 값의 순서가 다를 수 있다.

In [ ]:
for i in  {'muzi', 'con', 'apeach', 'jay-G', 'frodo', 'neo', 'tube', 'ryan', 'choonsik'}:
    print (i)

- 반복문 범위에 `튜플`을 넣을 수 있다. 변수 i가 튜플의 원소를 하나씩 순회한다.

In [ ]:
for i in ('banana', 'apple', 'coconut'):
    print (i)

### for~else
for문에도 else가 있다. while ~ else와 마찬가지로 for문이 정상적으로 모든 반복을 다 한 경우에만 실행한다.

```
for 변수 in 리스트(or 문자열 등) :
    statements1
    if 조건:
        if_statements
        break
    statements2
else:
    else_statements
next_statements
```

In [ ]:
a = 'computer'
letter = 'u'

for i in a:
    if i == letter:
        print(f'{letter}가 검색되었습니다.')
        break
else:
    print(f'{letter}는 검색되지 않았습니다.')
print('END')

## ➕comprehension(축약법)

- 리스트, 딕셔너리, 집합를 생성할 때 더 간결한 방법으로 생성하는 문법이다.
- 대괄호안에 for문이나 if문을 이용해 한 줄의 코드로 작성한다.
- 이러한 축약법은 파이썬이 `파이썬스럽다` 라는 것을 보여주는 대표적인 예이다.
- 아래 예를 통해 풀어 쓴 코드와 축약형 코드의 차이를 확인해보자.


In [ ]:
print('풀어 쓴 코드======')
x=[ ]
for i  in  range(1,11):
    x.append(i**2)
print(x)

print('축약형 코드======')
x=[i**2 for i  in  range(1,11)]
print(x)

In [ ]:
print('풀어 쓴 코드======')
x=[ ]
for i  in  ['70','90','100']:
     x.append(int(i))
print(x)

print('축약형 코드======')
print([int(i) for i in ['70','90','100']])

In [ ]:
my_dict = {'std1':'경영학과', 'std2':'컴공과', 'std3':'컴공과', 'std4':'영문과'}

my_dict2 = {i:j for i,j in my_dict.items() if j=='컴공과' }
print(my_dict2)

In [ ]:
my_dict = {'std1':'경영학과', 'std2':'컴공과', 'std3':'컴공과', 'std4':'영문과'}

my_dict2 = {i:j if j=='컴공과' else False for i,j in my_dict.items()  }
print(my_dict2)

## ➕가변(Mutable)자료형 vs. 불변(Immutable)자료형

:::{admonition} mutable vs. immutable  
:class: tip

가변(mutable)이라는 것은 객체가 만들어진 이후에도 데이터의 추가, 삽입, 삭제, 수정이 자유로운 특징을 가진 것을 의미한다. 리스트, 집합, 딕셔너리는 mutable 특징을 가진 데이터 타입이다.

불편(immutable)이라는 것은 객체가 한번 만들어진 이후에는 데이터의 추가, 삽입, 삭제, 수정이 불가하다는 것을 의미한다. 정수, 실수, 문자열, 튜플 등은 immutable 특징을 가진 데이터 타입이다.

:::

여기서는 mutable 데이터타입과 immutable 데이타 타입에 대해 좀 더 자세히 알아보도록 한다.

list, dict, set은 mutable 데이터타입에 속한다. mutable 데이타 타입은 객체가 만들어진 이후에도 value를 수정, 삭제, 추가가 가능하다.

반면, int, float, str, tuple은 immutable 데이타 타입이며 객체가 만들어지면 value를 수정, 삭제, 추가할 수 없는 타입을 의미한다.
우리는 예를들어, a=100을 한 후 a=200을 하면 int 변수인 a의 값을 변경할 수 있었으므로, int나 float의 value를 수정할 수 없다는 것이 선뜻 이해되지 않을 것이다.


<div align="center"><img src="https://haesunbyun.github.io/Core-Computing/_images/C_chapter4_mu.png" style="width:700px;"></div>


- 그렇다면 한번 확인해보자.
- 변수 a에 100을 저장하고, 변수 a의 ID를 출력해보자.
- 변수의 ID는 객체가 만들어질 때 정해진다.
- ID는 객체를 구분하는 구분자이며, 메모리상에서의 객체의 주소이다.

In [ ]:
a = 100
id(a)

- 변수 a에 100을 더하여 저장한 후, 다시 변수 a의 ID를 출력해보자.
- 이전에 출력되었던 값과 다른 ID가 출력되었을 것이다. 즉 새로운 ID가 생성되었다는 것을 의미하며 이는 객체가 새로 만들어졌다는 뜻이다.
- 변수 a는 `정수형 데이터 타입으로 객체가 만들어진 후에 value를 수정 할 수 없는 immutable 데이타 타입`이다. 따라서 100이 200으로 수정되는 것이 아니라 200을 가진 객체가 새로 생성된다.

In [ ]:
a += 100
id(a)

<div align="center"><img src="https://haesunbyun.github.io/Core-Computing/_images/C_chapter4_id.png" style="width:400px;"></div>


- 문자열 변수 str_data에 'Python Is fun'을 저장한 후 대문자 'I'를 소문자 'i'로 수정하려고 시도하면 에러가 나온다.
- `문자열도 객체가 만들어진 이후에는 수정할 수 없는 immutable 데이타 타입`이기 때문이다.


```python
str_data = 'Python Is fun'
str_data[7] = 'i'
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-01ff3e0289b1> in <module>
      1 str_data = 'Python Is fun'
----> 2 str_data[7] = 'i'

TypeError: 'str' object does not support item assignment
```

- 튜플 변수 std_ID의 인덱스 2의 값을 수정하려고 시도했다면 에러를 만나게 될 것이다.
- `튜플도 객체가 만들어진 이후에는 수정할 수 없는 immutable 데이타 타입`이기 때문이다.


```python
std_ID = ('23345', '23346', '23347', '23347')
std_ID[2] = '23348'
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-dd0d7a6d5119> in <module>
      1 std_ID = ('23345', '23346', '23347', '23347')
----> 2 std_ID[2] = '23348'

TypeError: 'tuple' object does not support item assignment
```


- mutable 데이터 타입인 리스트에 대해서 테스트해보자.
- 리스트변수 a에 [1,2,3]를 저장하고 ID를 출력해보자.

In [ ]:
a=[1,2,3,4]
id(a)

- 리스트변수 a에 새로운 값을 추가하고 ID를 출력해보자.
- 이전에 출력되었던 ID와 동일한 ID가 출력된 것을 볼 수 있다.
- 즉 `리스트는 mutable 데이터 타입이므로 데이터를 저장하기 위한 메모리가 가변이며 값을 수정, 추가, 삭제할 수 있다.`

In [ ]:
a.append(4)
print(a)
id(a)

## ➕얕은 복사 vs. 깊은 복사(Shallow Copy vs. Deep Copy)
리스트, 딕셔너리, 집합, 배열 등의 데이터를 복사해서 복사된 데이터를 가지고 작업하기를 원할 때가 있다.
이들은 모두 mutable 데이터타입이고, 이들 자료구조를 복사할 때의 문제점과 방법을 알아보자.

데이터를 복사하는 방법에는 세 가지가 있다.
- 변수복사: 원조변수와 복사변수가 같은 메모리를 참조
- Shallow Copy : 원조변수와 복사변수가 다른 메모리를 참조하나 2차원 이상인 경우 동일 메모리를 참조
- Deep Copy : 복사변수는 새로운 메모리를 할당하여 독립적으로 생성

### 일반복사

- `cp_a = a`와 같은 복사할 수 있다.
- 그러나 이와 같은 복사의 문제는 복사 배열의 데이터를 작업을 하면 원조 배열의 데이터도 똑같이 작업된다는 것이다.
- 그 이유는 복사변수와 원조변수가 같은 메모리 주소를 참조하기 때문이다.

<div align="center"><img src="https://haesunbyun.github.io/Core-Computing/_images/C_chapter4_id3.png" style="width:400px;"></div>


- 다음 코드를 통해 확인해보자.
- 리스트, 딕셔너리, 집합, 배열 각각에 변수 a, b, c, d를  정의하였다.


In [ ]:
a=[1,2,3,[10,20,30]] #리스트
b={'a':1, 'b':2, 'c':[10,20,30]} #딕셔너리
c={1,2,3,(10,20,30)} # 집합
d=np.array([[1,2,3],[10,20,30]]) #배열

print('Origin Data===================')
print(f'리스트: {a}')
print(f'딕셔너리: {b}')
print(f'집합: {c}')
print(f'배열: {d}')

- 위에서 정의한 변수 a, b, c, d를 변수 a1, b1, c1,d1에 각각 복사하였다.

In [ ]:
a1=a
b1=b
c1=c
d1=d
print('Copy Data=============')
print(f'리스트: {a1}')
print(f'딕셔너리: {b1}')
print(f'집합: {c1}')
print(f'배열: {d1}')

- 복사한 변수 a1, b1, c1, d1의 값의 일부를 수정하였다.

In [ ]:
a1[1]=100 # 리스트 수정
b1['b']=100 # 딕셔너리 수정
c1.update((5,6,7)) # 집합 수정
d1[0][1]=100 # 배열 수정

- 원조변수 a, b, c, d와 복사변수 a1, b1, c1, d1을 출력해보면, `원조변수의 값까지 수정된 것을 확인할 수 있다.`

In [ ]:
print('Copy Data 수정 후 origin data=============')
print(f'리스트: {a}')
print(f'딕셔너리: {b}')
print(f'집합: {c}')
print(f'배열: {d}')

print('\nCopy Data 수정 후 copy data=============')
print(f'리스트: {a1}')
print(f'딕셔너리: {b1}')
print(f'집합: {c1}')
print(f'배열: {d1}')

- 원조변수와 복사변수의 ID가 동일한지 알아보기 위해 is 연산자를 사용하여 확인해볼 수 있다.
- is 연산자는 메모리 주소 즉 객체의 ID가 동일한지 확인하는 연산자이다.
- 값이 동일한지 확인하는 것은 `==`를 사용하고, ID가 동일한지 확인하기 위해서는 is 연산자를 사용한다.

In [ ]:
print(a is a1)
print(b is b1)
print(c is c1)
print(d is d1)

### copy() 메서드(shallow copy)


- 원조데이터가 수정되는 것을 방지하기 위해서는 copy() 메서드를 사용해보자.
- 리스트, 딕셔너리, 집합, 배열 각각에 변수 a, b, c, d를 정의하였다.

In [ ]:
a=[1,2,3,[10,20,30]] #리스트
b={'a':1, 'b':2, 'c':[10,20,30]} #딕셔너리
c={1,2,3,(10,20,30)} # 집합
d=np.array([[1,2,3],[10,20,30]]) # 배열

print('Origin Data===================')
print(f'리스트: {a}')
print(f'딕셔너리: {b}')
print(f'집합: {c}')
print(f'배열: {d}')

- 이번에는 copy() 메서드를 사용하여 복사하였다.

In [ ]:
a1=a.copy()
b1=b.copy()
c1=c.copy()
d1=d.copy()
print('Copy Data=============')
print(f'리스트: {a1}')
print(f'딕셔너리: {b1}')
print(f'집합: {c1}')
print(f'배열: {d1}')

- 복사한 변수 a1, b1, c1, d1의 값의 일부를 수정하였다.

In [ ]:
a1[1]=100 # 리스트 수정
b1['b']=100 # 딕셔너리 수정
c1.update((5,6,7)) # 집합 수정
d1[0][1]=100 # 배열 수정

- 원조변수 a, b, c, d와 복사변수 a1, b1, c1, d1을 출력해보면, 원조변수의 값은 그대로 유지되고, 복사변수의 값만 수정된 것을 확인할 수 있다.

In [ ]:
print('Copy Data 수정 후 origin data=============')
print(f'리스트: {a}')
print(f'딕셔너리: {b}')
print(f'집합: {c}')
print(f'배열: {d}')

print('\nCopy Data 수정 후 copy data=============')
print(f'리스트: {a1}')
print(f'딕셔너리: {b1}')
print(f'집합: {c1}')
print(f'배열: {d1}')

- 또한 원조변수 a, b, c, d와 복사변수 a1, b1, c1, d1가 서로 다른 ID를 갖고 있는 것을 확인할 수 있다.

In [ ]:
print(a is a1)
print(b is b1)
print(c is c1)
print(d is d1)

- 하지만 결론부터 말하면 리스트의 아이템이 mutable 데이터이거나 딕셔너리의 value가 mutable 데이터인 경우 이를 수정했을 때 여전히 원조변수의 값이 같이 수정되는 문제가 발생한다.


```
a=[1,2,3,[10,20,30]]
b={'a':1, 'b':2, 'c':[10,20,30]}
c=np.array([{'a':[1,2]},{'b':[1,2]},{'c':[1,2]}])
```
a[3]의 값이 [10,20,30]리스트로 mutable 데이터이다.

b['c']의 값이 [10,20,30]리스트로 mutable 데이터이다.

c의 각 원소들이 딕셔너리로 mutable 데이터이다.


In [ ]:
a=[1,2,3,[10,20,30]]
b={'a':1, 'b':2, 'c':[10,20,30]}
c=np.array([{'a':[1,2]},{'b':[1,2]},{'c':[1,2]}])

In [ ]:
a1=a.copy()
b1=b.copy()
c1=c.copy()

In [ ]:
a1[3][0]='here'
b1['c'][0]='here'
c1[0]['a'][0]=100

- 원본 데이터와 복사 데이터가 모두 수정된 것을 확인할 수 있다.

In [ ]:
print(a, a1)
print(b, b1)
print(c, c1)

<div align="center"><img src="https://haesunbyun.github.io/common/images/C_chapter4_id4.png" width=300></div>

### Deepcopy()
- deepcopy() 함수는 copy 모듈에 있다.
- Deep copy는 복사변수의 값을 작업(수정, 삭제, 추가 등)해도 원본변수의 값이 작업되지 않는다.

In [ ]:
a=[1,2,3,[10,20,30]]
b={'a':1, 'b':2, 'c':[10,20,30]}
c=np.array([{'a':[1,2]},{'b':[1,2]},{'c':[1,2]}])

In [ ]:
import copy
a1=copy.deepcopy(a)
b1=copy.deepcopy(b)
c1=copy.deepcopy(c)
a1[3][0] = 100
b1['c'][0] = 100
c1[0]['a'][0] = 100

print('Copy Data 수정 후 origin data=============')
print(a)
print(b)
print(c)

print('\nCopy Data 수정 후 copy data=============')
print(a1)
print(b1)
print(c1)


## 마무리
- 프로그래밍 제어 구조는 순차, 선택, 반복 구조가 있다.
- 조건문은 비교할 때 사용하는 문으로 if문, if ~ else문, if ~ elif ~ else문이 있다.
- 비교연산자에는 >, < , >=, <=, ==, != 연산자가 있다.
- 논리연산자에는 and, or, not 연산자가 있다.
- 멤버연산자에는 in, not in 연산자가 있다.
- while문은 조건비교 결과가 True인 동안 블록 소스코드를 반복 수행한다.
- for문은 범위의 처음부터 끝까지 차례대로 반복한다.
- 코드 축약법을 활용하면 코드의 가독성과 효율성을 높일 수 있으므로, 반복적인 패턴이나 불필요한 코드를 줄일 수 있다.
- 복합자료형의 특성과 가변/불변 자료형을 이해하면 메모리 관리와 데이터 조작에서 발생할 수 있는 오류를 줄일 수 있다.
- 얕은 복사와 깊은 복사의 차이를 명확히 이해하고 적절하게 활용하는 것은 데이터의 의도치 않은 변경을 방지하는 데 중요하다.

---
<font color='Grey' size="4">
F37.204 컴퓨팅 핵심: 컴퓨터로 생각하기(Core Computing: Thinking with Computers)</font>

---
서울대학교 학부대학<br>
교수 변해선